### ISSUE TITLE
SSH Key Management Page Is Missing Links

### ISSUE THREAD

**Issue by cipherbytes9** [CloudA/knowledgebase#7]
While using the page - http://docs.clouda.ca/101/ssh-key-management
There is mention of links throughout the text but there are no actual links. Examples - 

You can optionally provide a password to protect your key, by leaving the password field empty you'll choose to not set one. Once your key is generated, make sure you never share your private key at ~/.ssh/id_rsa, and whenever prompted for your SSH key, you provide the contents of your public key located at ~/.ssh/id_rsa.pub. If you'd like more information on SSH a good overview is available here.

The "SSH a good overview is available here." should have a link to whatever source you are trying to reference.

Another example - 

If you haven't configured your OpenStack command line tools yet read this article before continuing.

This line should be directing to OpenStack links for more information but is not.

**Comment by hyprbst** [comment]
Good catch, must have missed those links on the migration from the old platform while copying content.

**Comment by jacobgodin** [comment]
@hyprbst are you working on this still?

**Comment by swat30** [comment]
@hyprbst are you working on this still?
